# Generated by Django 5.1.2 on 2024-11-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('customer', 'group', 'date')},
        ),
    ]
